[[protocols]]
name = "mxq4k"
protocol = "nec"
variant = "necx"
[protocols.scancodes]
0xcc1d11 = "KEY_OK"
0xcc1d0f = "KEY_BACK"
0xcc1d07 = "KEY_UP"
0xcc1d44 = "KEY_DOWN"
0xcc1d10 = "KEY_LEFT"
0xcc1d12 = "KEY_RIGHT"
0xcc1d0e = "KEY_VOLUMEUP"
0xcc1d02 = "KEY_VOLUMEDOWN"
0xcc1d00 = "KEY_POWER"
0xcc1d0c = "KEY_MUTE"
0xcc1d40 = "KEY_C"
0xcc1d41 = "KEY_1"
0xcc1d45 = "KEY_2"
0xcc1d4d = "KEY_3"
0xcc1d42 = "KEY_4"
0xcc1d46 = "KEY_5"
0xcc1d4e = "KEY_6"
0xcc1d43 = "KEY_7"
0xcc1d47 = "KEY_8"
0xcc1d4f = "KEY_9"
0xcc1d49 = "KEY_0"
0xcc1d4a = "KEY_BACKSPACE"
0xcc1d01 = "KEY_M"
0xcc1d05 = "KEY_T"
0xcc1d09 = "KEY_E"
0xcc1d0d = "KEY_A"
0xcc1d06 = "KEY_PAGEDOWN"
0xcc1d0a = "KEY_PAGEUP"
0xcc1d03 = "KEY_HOME"
0xcc1d4c = "KEY_INFO"
0xcc1d48 = "KEY_O"
