[[protocols]]
name = "conf1"
protocol = "nec"
variant = "nec"
[protocols.scancodes]
0x140 = "KEY_POWER"
0x118 = "KEY_VOLUMEUP"
0x110 = "KEY_VOLUMEDOWN"
0x141 = "KEY_MUTE"
0x100 = "KEY_MENU"
0x119 = "KEY_BACK"
0x116 = "KEY_UP"
0x151 = "KEY_LEFT"
0x150 = "KEY_RIGHT"
0x11a = "KEY_DOWN"
0x113 = "KEY_OK"
0x111 = "KEY_HOME"
0x14b = "KEY_PREVIOUS"
0x14c = "KEY_INFO"
0x14f = "KEY_NEXT"
0x159 = "KEY_PREVIOUS"
0x15a = "KEY_PLAYPAUSE"
0x158 = "KEY_NEXT"
0x147 = "KEY_MENU"
0x101 = "KEY_NUMERIC_0"
0x142 = "KEY_BACKSPACE"
0x14e = "KEY_NUMERIC_1"
0x10d = "KEY_NUMERIC_2"
0x10c = "KEY_NUMERIC_3"
0x14a = "KEY_NUMERIC_4"
0x109 = "KEY_NUMERIC_5"
0x108 = "KEY_NUMERIC_6"
0x146 = "KEY_NUMERIC_7"
0x105 = "KEY_NUMERIC_8"
0x104 = "KEY_NUMERIC_9"

[[protocols]]
name = "conf2"
protocol = "nec"
variant = "necx"
[protocols.scancodes]
0x40404d = "KEY_POWER"
0x404043 = "KEY_MUTE"
0x404017 = "KEY_VOLUMEDOWN"
0x404018 = "KEY_VOLUMEUP"
0x40400b = "KEY_UP"
0x404010 = "KEY_LEFT"
0x404011 = "KEY_RIGHT"
0x40400e = "KEY_DOWN"
0x40400d = "KEY_OK"
0x40401a = "KEY_HOME"
0x404045 = "KEY_INFO"
0x404042 = "KEY_BACK"
0x404001 = "KEY_1"
0x404002 = "KEY_2"
0x404003 = "KEY_3"
0x404004 = "KEY_4"
0x404005 = "KEY_5"
0x404006 = "KEY_6"
0x404007 = "KEY_7"
0x404008 = "KEY_8"
0x404009 = "KEY_9"
0x404047 = "KEY_SUBTITLE"
0x404000 = "KEY_0"
0x40400c = "KEY_BACKSPACE"

[[protocols]]
name = "conf3"
protocol = "nec"
variant = "necx"
[protocols.scancodes]
0xcc1d11 = "KEY_OK"
0xcc1d0f = "KEY_BACK"
0xcc1d07 = "KEY_UP"
0xcc1d44 = "KEY_DOWN"
0xcc1d10 = "KEY_LEFT"
0xcc1d12 = "KEY_RIGHT"
0xcc1d0e = "KEY_VOLUMEUP"
0xcc1d02 = "KEY_VOLUMEDOWN"
0xcc1d00 = "KEY_POWER"
0xcc1d0c = "KEY_MUTE"
0xcc1d40 = "KEY_C"
0xcc1d41 = "KEY_1"
0xcc1d45 = "KEY_2"
0xcc1d4d = "KEY_3"
0xcc1d42 = "KEY_4"
0xcc1d46 = "KEY_5"
0xcc1d4e = "KEY_6"
0xcc1d43 = "KEY_7"
0xcc1d47 = "KEY_8"
0xcc1d4f = "KEY_9"
0xcc1d49 = "KEY_0"
0xcc1d4a = "KEY_BACKSPACE"
0xcc1d01 = "KEY_M"
0xcc1d05 = "KEY_T"
0xcc1d09 = "KEY_E"
0xcc1d0d = "KEY_A"
0xcc1d06 = "KEY_PAGEDOWN"
0xcc1d0a = "KEY_PAGEUP"
0xcc1d03 = "KEY_HOME"
0xcc1d4c = "KEY_INFO"
0xcc1d48 = "KEY_O"

[[protocols]]
name = "onetv_lite"
protocol = "NEC"
[protocols.scancodes]
0x19 = "KEY_MUTE"
0x18 = "KEY_MEDIA"
0x13 = "KEY_VOLUMEUP"
0x17 = "KEY_VOLUMEDOWN"
0x0d = "KEY_HOME"
0x05 = "KEY_BACK"
0x06 = "KEY_UP"
0x5a = "KEY_LEFT"
0x1a = "KEY_OK"
0x1b = "KEY_RIGHT"
0x16 = "KEY_DOWN"
0x45 = "KEY_MENU"
0x12 = "KEY_INFO"
0x0f = "KEY_NUMERIC_0"
0x52 = "KEY_NUMERIC_1"
0x50 = "KEY_NUMERIC_2"
0x10 = "KEY_NUMERIC_3"
0x56 = "KEY_NUMERIC_4"
0x54 = "KEY_NUMERIC_5"
0x14 = "KEY_NUMERIC_6"
0x4e = "KEY_NUMERIC_7"
0x4c = "KEY_NUMERIC_8"
0x0c = "KEY_NUMERIC_9"
0x21 = "KEY_NUMERIC_STAR"
0x51 = "KEY_BACKSPACE"
0x59 = "KEY_POWER"

[[protocols]]
name = "greenet"
protocol = "nec"
variant = "nec"
[protocols.scancodes]
0xdf1c = "KEY_POWER"
0xdf4b = "KEY_REWIND"
0xdf4f = "KEY_FORWARD"
0xdf01 = "KEY_PLAYPAUSE"
0xdf5f = "KEY_MENU"
0xdf5d = "KEY_VOLUMEUP"
0xdf5c = "KEY_VOLUMEDOWN"
0xdf42 = "KEY_HOME"
0xdf0a = "KEY_BACK"
0xdf1a = "KEY_UP"
0xdf48 = "KEY_DOWN"
0xdf07 = "KEY_RIGHT"
0xdf47 = "KEY_LEFT"
0xdf06 = "KEY_OK"
0xdf03 = "KEY_ANGLE"
0xdf18 = "KEY_CONTEXT_MENU"
0xdf54 = "KEY_1"
0xdf16 = "KEY_2"
0xdf15 = "KEY_3"
0xdf50 = "KEY_4"
0xdf12 = "KEY_5"
0xdf11 = "KEY_6"
0xdf4c = "KEY_7"
0xdf0e = "KEY_8"
0xdf0d = "KEY_9"
0xdf41 = "KEY_MUTE"
0xdf0c = "KEY_0"
0xdf10 = "KEY_BACKSPACE"
